### ISSUE TITLE
Passing parameters to validation stylesheet fails

### ISSUE THREAD

**Issue by dmj** [schxslt/schxslt#97]
See error one and two in https://github.com/schxslt/schxslt/issues/96

**Comment by dmj** [comment]
The root issue seems to be some problem with Xalan:

```xml
<testcase name="validate-with-xslt" time="PT0.073S">
      <error line="94" column="89" uri="file:///home/dmaus/projects/schxslt/src/main/xquery/basex/content/schxslt.xqm" type="xslt:error">
        <info>javax.xml.transform.TransformerConfigurationException: Translet-Klasse "compile_for_svrl" konnte nicht geladen werden.
        at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.defineTransletClasses(TemplatesImpl.java:433)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.getTransletInstance(TemplatesImpl.java:451)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.newTransformer(TemplatesImpl.java:486)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:762)
        at org.basex.query.func.xslt.XsltTransform.transformer(XsltTransform.java:127)
        at org.basex.query.func.xslt.XsltTransform.transform(XsltTransform.java:103)
        at org.basex.query.func.xslt.XsltTransform.transform(XsltTransform.java:59)
        at org.basex.query.func.xslt.XsltTransform.item(XsltTransform.java:37)
        at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:48)
        at org.basex.query.expr.gflwor.GFLWOR$1.next(GFLWOR.java:92)
        at org.basex.query.QueryContext.next(QueryContext.java:400)
        at org.basex.query.expr.TypeCheck$1.next(TypeCheck.java:99)
        at org.basex.query.QueryContext.next(QueryContext.java:400)
        at org.basex.query.expr.ParseExpr.item(ParseExpr.java:55)
        at org.basex.query.expr.ParseExpr.toItem(ParseExpr.java:455)
        at org.basex.query.func.StandardFunc.toNodeOrAtomItem(StandardFunc.java:326)
        at org.basex.query.func.xslt.XsltTransform.read(XsltTransform.java:76)
        at org.basex.query.func.xslt.XsltTransform.transform(XsltTransform.java:51)
        at org.basex.query.func.xslt.XsltTransform.item(XsltTransform.java:37)
        at org.basex.query.expr.ParseExpr.value(ParseExpr.java:71)
        at org.basex.query.expr.If.value(If.java:131)
        at org.basex.query.expr.gflwor.Let$LetEval.next(Let.java:175)
        at org.basex.query.expr.gflwor.GFLWOR$1.next(GFLWOR.java:88)
        at org.basex.query.QueryContext.next(QueryContext.java:400)
        at org.basex.query.scope.MainModule$1.next(MainModule.java:122)
        at org.basex.query.QueryContext.next(QueryContext.java:400)
        at org.basex.query.func.unit.Unit.eval(Unit.java:293)
        at org.basex.query.func.unit.Unit.test(Unit.java:145)
        at org.basex.query.func.unit.Suite.test(Suite.java:54)
        at org.basex.core.cmd.Test.run(Test.java:37)
        at org.basex.core.Command.run(Command.java:257)
        at org.basex.core.Command.execute(Command.java:93)
        at org.basex.api.client.LocalSession.execute(LocalSession.java:132)
        at org.basex.api.client.Session.execute(Session.java:36)
        at org.basex.core.CLI.execute(CLI.java:92)
        at org.basex.core.CLI.execute(CLI.java:76)
        at org.basex.core.CLI.execute(CLI.java:63)
        at org.basex.BaseX.&lt;init&gt;(BaseX.java:80)
        at org.basex.BaseX.main(BaseX.java:42)</info>
      </error>
    </testcase>
```
